sonar.projectKey=mjahsan_actual-iot-web-application
sonar.organization=mjahsan

sonar.sources=dashboard_app,data_simulator

sonar.python.version=3.11

sonar.python.coverage.reportPaths=coverage/coverage_results.xml

sonar.python.xunit.reportPath=tests/pytest_results.xml