name: Workflow Web Application

on: 
  push:
    branches:
      - 'feature/*'
    branches-ignore:
      - 'main'

jobs:
    Unit Tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v7

            - name: Python Runtime
              uses: actions/setup-python@v6
              with:
                python-version: '3.13' 
              
            - name: List files
              run: ls
