name: Workflow Web Application

on: 
  push:
    branches:
      - 'feature/*'

jobs:
    Unit-Tests:
        runs-on: ubuntu-latest
        timeout-minutes: 2
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v7

            - name: Python Runtime
              uses: actions/setup-python@v6
              with:
                python-version: '3.13' 

            - name: Installing dependencies
              run: pip install -r ./tests/requirements.txt
              
            - name: App and Simulator tests
              run: |
                pytest tests/ \
                --junitxml=pytest_results.xml \
                --cov=dashboard_app \
                --cov=data_simulator \
                --cov-report=term-missing \
                --cov-report=xml:coverage_results.xml \
                --cov-fail-under=80
            
            - name: Archive Test & Coverage Results
              uses: actions/upload-artifact@v4
              if: always()
              with:
                name: pytest_and_coverage_results
                path: |
                  tests/pytest_results.xml
                  coverage/coverage_results.xml


