name: Workflow Web Application

on: 
  push:
    branches:
      - 'feature/*'

jobs:
    Unit-Tests:
        runs-on: ubuntu-latest
        timeout-minutes: 2
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v7

            - name: Python Runtime
              uses: actions/setup-python@v6
              with:
                python-version: '3.13' 

            - name: Installing dependencies
              run: pip install -r ./tests/requirements.txt
              
            - name: App and Simulator tests
              run: |
                pytest tests/ \
                --cov=dashboard_app \
                --cov=data_simulator \
                --cov-report=term-missing \
                --cov-fail-under=80
